import { Inter } from "next/font/google";
import "./globals.css";
import "../amplify-config";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        <div className='py-8 px-16 bg-slate-100'>
          {children}
        </div>
      </body>
    </html>
  );
}
