
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import RootLayoutThatConfiguresAmplifyOnTheClient from "./amplify-config";
import "./globals.css";
import '@aws-amplify/ui-react/styles.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <RootLayoutThatConfiguresAmplifyOnTheClient>
          <>
            <Navbar />
            <div className='py-8 px-16 bg-slate-100'>
              {children}
            </div>
          </>
        </RootLayoutThatConfiguresAmplifyOnTheClient>

      </body>
    </html>
  );
}
